#!/bin/bash

mkdir -p ~/.config/dev/current/colorschemes


if [ -L ~/.config/dev/current/hyprland.conf ]; then
    current=$(readlink ~/.config/dev/current/hyprland.conf)
    current_name=$(basename "$(dirname "$current")")
else
    current_name=""
fi


colorschemes=(~/.config/dev/current/colorschemes/*/)
colorschemes=("${colorschemes[@]%/}")
colorschemes=("${colorschemes[@]##*/}")

if [ ${#colorschemes[@]} -eq 0 ]; then
    exit 0
fi

current_index=-1
for i in "${!colorschemes[@]}"; do
    if [ "${colorschemes[$i]}" = "$current_name" ]; then
        current_index=$i
        break
    fi
done

if [ $current_index -eq -1 ]; then
    next_index=0
else
    next_index=$(( (current_index + 1) % ${#colorschemes[@]} ))
fi

result="${colorschemes[$next_index]}"

if [ -n "$result" ]; then
    dir="$result"
    for file in ~/.config/dev/current/colorschemes/"$dir"/*; do
        filename=$(basename "$file")
        if [ "$filename" != "preview.png" ] && [ -f "$file" ]; then
            ln -sf "$file" ~/.config/dev/current/"$filename"
        fi
    done
fi
hyprctl reload > /dev/null
makoctl reload
restart waybar
reload-ghostty > /dev/null
reload-rofi
notify-send "Colorscheme Changed" "$result"
