#!/bin/bash

f(){ 
    if [ -z "$1" ]; then
        echo "Usage: gc <git-repository-url>"
        return 1
    fi
    username=$(echo "$1" | sed -n "s|.*github\.com[/:]\\([^/]*\\)/.*|\\1|p")
    repo=$(basename "$1" .git)
    mkdir -p ~/workspace/github/"$username"
    cd ~/workspace/github/"$username"
    git clone "$1"
    tmux new-session -d -s "$repo" -c "$repo" -n home ";" new-window -c "$repo" -n zsh ";" select-window -t home
    unset -f f
    cd -
}
f "$@"
