#!/bin/bash

uwsm app -- ghostty --class=flo.ting --config-file=~/.local/share/dev/default/ghostty/floating -e zsh -ic "yay -Qq | fzf --multi --preview 'yay -Qi {}' --preview-window=bottom:40% | xargs -r yay -R --noconfirm && show-done"
