#!/bin/bash

selected_dir=$(find ~ -type d 2>/dev/null | fzf --prompt="Select directory: ") && tmux new-session -s $(basename "$selected_dir") -c $selected_dir -n home ";" new-window -c $selected_dir -n zsh ";" select-window -t home
