#!/bin/bash

cp scripts/* ~/.local/bin/
cp -r default/ ~/.local/share/dev/
rsync -av --exclude='*/extra' themes/ ~/.local/share/dev/themes/ > /dev/null 2>&1

# Sync backgrounds added with the add-background command
cp -P ~/.local/share/dev/themes/dark/extra/* themes/dark/extra/
cp -P ~/.local/share/dev/themes/light/extra/* themes/light/extra/
