alias vim='nvim'
alias ytpl='yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" "$1"'
alias zsh='nvim ~/.zshrc'
alias zz='source ~/.zshrc && echo Config reloaded'
alias a='cd && clear'
alias d='cd $(find . -type d -name ".git" -prune -o -type d -print | fzf) && ls'
alias n='nvim .'
alias cc='cd ~/.config && config-notify && nvim .'
alias ch='cd ~/.config/hypr && config-notify && nvim .'
alias cs='cd ~/.config/shell && config-notify && nvim .'
alias cn='cd ~/.config/nvim && config-notify && nvim .'
alias cg='cd ~/.config/ghostty && config-notify && nvim .'
alias cw='cd ~/.config/waybar && config-notify && nvim .'
alias ls='lsd'
alias nv='nvim $(fzf -m --preview="bat --color=always {}")'
alias tt='tmux new-session -d -s dev -c ~ -n nvim ";" new-window -c ~ -n zsh ";" select-window -t nvim'
alias activate='source .venv/bin/activate --active'
alias paint='kitty icat'
alias ti='tmux-init-dir-sesh'
alias tid='tmux-init-dir-sesh-d'
alias ta='tmux-fzf-attach-sesh'
alias tk='tmux-fzf-kill-sesh'
alias gc='git-clone-sesh'
alias gcd='git-clone-sesh-d'
