#!/bin/bash

yay -S --noconfirm hyprland hyprlock hypridle hyprsunset zen-browser-bin ungoogled-chromium-bin hyprshot python bluetui impala pavucontrol brightnessctl playerctl ttf-font-awesome ttf-jetbrains-mono-nerd ttf-nerd-fonts-symbols gum

mkdir -p ~/.config
mkdir -p ~/.local/share/dev
mkdir -p ~/workspace
git clone https://github.com/rmuell9/linux ~/.config
mv ~/.config/linux/hypr ~/.config/hypr
