#!/bin/bash

yay -S --noconfirm - < packages.txt

mkdir -p ~/.config
mkdir -p ~/.local/share/dev
mkdir -p ~/workspace
git clone https://github.com/rmuell9/linux ~/.config
rm -rf ~/.config/hypr
mv ~/.config/linux/hypr ~/.config/hypr
