#!/bin/bash

mkdir -p ~/.config/dev/current/extra

result=$(fzf --preview='kitty icat \
    --clear \
    --transfer-mode=memory \
    --align center \
    --stdin=no \
    --unicode-placeholder \
    --place=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}@0x0 \
    {}'\
    --preview-window=right:70% \
    )

if [ -n "$result" ]; then
    cp $(realpath $result) ~/.config/dev/current/extra
fi
