#!/bin/bash
   
mkdir -p ~/.config/dev/current/extra

result=$(cd ~/.config/dev/current/extra && fzf --preview='kitty icat \
    --clear \
    --transfer-mode=memory \
    --align center \
    --stdin=no \
    --unicode-placeholder \
    --place=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}@0x0 \
    {}'\
    --preview-window=right:70% \
    )

if [ -n "$result" ]; then
    rm -f ~/.config/dev/current/background.png
    ln -s "$(realpath ~/.config/dev/current/extra/$result)" ~/.config/dev/current/background.png
    restart hyprpaper
fi
