#!/bin/bash

uwsm app -- ghostty --class=flo.ting --config-file=~/.local/share/dev/default/ghostty/floating -e zsh -ic "yay -Slq | fzf --query='' --preview 'yay -Si {}' --preview-window=bottom:40% --multi --bind 'tab:toggle+down' | xargs -r -I {} zsh -c 'yay -S {} --noconfirm' && show-done"
