#!/bin/bash

# Check current theme
current=$(gsettings get org.gnome.desktop.interface gtk-theme)

if [[ $current == "'Adwaita'" ]]; then
    # Switch to dark gnome theme
    gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
    gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"

    hyprctl hyprpaper unload "~/.config/dev/current/background.png"
    
    rm -rf ~/.config/dev/current
    ln -s ~/.local/share/dev/themes/dark ~/.config/dev/current

    hyprctl reload
    makoctl reload
    notify-send "Dark Mode"
    
    #Switch wallpapers
    hyprctl hyprpaper preload "~/.config/dev/current/background.png"
    hyprctl hyprpaper wallpaper "eDP-1,~/.config/dev/current/background.png"

    restart waybar
    reload-ghostty
    reload-rofi

elif [[ $current == "'Adwaita-dark'" ]]; then

    # Switch to light gnome theme
    gsettings set org.gnome.desktop.interface gtk-theme "Adwaita"
    gsettings set org.gnome.desktop.interface color-scheme "prefer-light"

    hyprctl hyprpaper unload "~/.config/dev/current/background.png"

    rm -rf ~/.config/dev/current
    ln -s ~/.local/share/dev/themes/light ~/.config/dev/current

    hyprctl reload
    makoctl reload
    notify-send "Light Mode"

    #Switch wallpapers
    hyprctl hyprpaper preload "~/.config/dev/current/background.png"
    hyprctl hyprpaper wallpaper "eDP-1,~/.config/dev/current/background.png"

    restart waybar
    reload-rofi
    reload-ghostty
fi
